title: Project Euler
email: johnwill.domingo@gmail .com
description: A compilation of my solutions to the coding challenges found on projecteuler.net.
baseurl: "/projecteuler/" # the subpath of your site, e.g. /blog/
url: "http://johndomingo.com" # the base hostname & protocol for your site
twitter_username: jwdomingo
github_username:  jwdomingo

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title
